trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copia i file .war generati nella cartella di destinazione
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target' # Controlla questo percorso
    Contents: '**/*.war' # Specifica che vogliamo copiare solo i file .war
    TargetFolder: '$(Build.ArtifactStagingDirectory)' # Copia i file nella cartella di staging dell'artifact

# Pubblica l'artifact della build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)' # Usa la cartella di staging dell'artifact come percorso da pubblicare
    ArtifactName: 'drop' # Nome dell'artifact
    publishLocation: 'Container' # Pubblica l'artifact nel contenitore di Azure DevOps